### PR TITLE
Update to phenomic@0.19

### PR DESCRIPTION
**Pull request by jeddy3**
- Updates to phenomic@0.19.5, which fixes the hash links. Closes https://github.com/stylelint/stylelint.io/issues/25
- Uses the phenomic default theme directory structure, styles and configuration _as much as possible_ to reduce the maintenance burden of keeping the website up to date.
- Uses two custom phenomic loader plugins (one of which includes two custom remark plugins) to prepare the github repo markdown files for use in the website:
  - The first loader plugin uses the first line (i.e. the first heading) of each markdown file as the `title`.
  - The second adapts phenomic markdown-to-html loader plugin to include two custom remark plugins. 
     - The first of which rewrites urls for the website directory structure.  This replaces the [previous method](https://github.com/stylelint/stylelint.io/tree/5e9bcfe69a58bd57fbece877543f663d43f54c0d/scripts/process-docs-lib), which processed the files as strings rather than as strings _within an AST_.  The new approach affords more accuracy and closes https://github.com/stylelint/stylelint.io/issues/6. 
    - The second adds appropriate classes to the valid and invalid code pattern examples. This replaces the [previous method](https://github.com/stylelint/stylelint.io/blob/f38a22e9a234f1a314982d56926ae6f5d172a0ce/web_modules/layouts/Page/index.js), which transformed the _HTML_ after mounting. This new approach allows us to use the stateless Page component untouched from the default phenomic theme.
- Ports over the DocSearch component from phenomic doc site to provide search. Closes https://github.com/stylelint/stylelint.io/issues/1
- Increases the font-size of the text within the navigation and increases the touch area. Closes https://github.com/stylelint/stylelint.io/issues/27
- Adds “processors” to the navigation. Closes https://github.com/stylelint/stylelint.io/issues/26

I wanted to write-up the key changes as this is pretty much a rewrite and there are a lot of diffs. Likely making this PR tricky to review. 

Feel free to pull down this branch and have a poke around. I intend to push it live over the weekend as it addresses a few outstanding issues, especially the broken hash links.

### CODE REVIEW

**Comment by MoOx** [comment]
A screenshot is missing :D

**Comment by davidtheclark** [comment]
@jeddy3 I think maybe we should merge this PR, in order to get your massive, systemic changes in, and then QA and file separate issues for anything we find. Sound good?

**Comment by jeddy3** [comment]
Rules page at a wider viewport:

screen shot 2016-11-25 at 22 22 24

Searching:

screen shot 2016-11-25 at 22 23 24

Narrow viewport:

screen shot 2016-11-25 at 22 24 11

--- 

@MoOx Once again, a big thank you for both your help and for your continued work on phenomic. It was a joy to work with :)

**Comment by davidtheclark** [comment]
@jeddy3 @MoOx I'm not sure the hash problem is fully resolved. If I click a header, I am not sent to the top of the page — that's true; but if I then refresh, the page does not load at that header, which is what I would expect. It just loads at the top of the page.

**Comment by davidtheclark** [comment]
Site search seems to work great!

**Comment by jeddy3** [comment]
> I'm not sure the hash problem is fully resolved

Oh, that's odd. I think that behaviour was working in `0.19.4`, so I neglected to test it in `0.19.5`. I can replicate the problem. Do we merge anyway as anchoring _from within the site_ does work, which is definitely a step in the right direction from the current site?

**Comment by davidtheclark** [comment]
>  Do we merge anyway

Yep. It's an improvement over what we have now.

**Comment by ntwb** [comment]
Very nice 🎉

**Comment by MoOx** [comment]
> If I click a header, I am not sent to the top of the page — that's true; but if I then refresh, the page does not load at that header, which is what I would expect. It just loads at the top of the page.

- If you click to a hash, you should have the normal browser behavior.
- then if you scroll and refresh, you should still have normal browser behavior (which might depends on the browser ⚠️) but most of the time you should have the previous scroll restored
- if you open an url directly with the hash, you should have normal browser behavior (go to the hash)

The tricky part that was "hard" to handle was when we click on an internal link that have a hash: we need to wait for data to actually simulate the browser behavior (which is: scroll to the corresponding id/name). This part should be covered too

I may have missed some stuff, but we have more test than ever to cover all cases I can think of: https://github.com/MoOx/phenomic/blob/master/src/client/__tests__/should-update-scroll.js

Let me know if you still really think there is an issue (a good way to check if it's a browser behavior or phenomic bug is to disable JS and compare on (production) static version :)

**Comment by jeddy3** [comment]
@MoOx Thanks for writing this up!

> (a good way to check if it's a browser behavior or phenomic bug is to disable JS and compare on (production) static version :)

That's a great suggestion and one I just tried. Chrome's default behaviour (i.e. with JS off) was pretty peculiar when refreshing with a hash present: on one occasion the scroll stayed still, but otherwise it jumps back to the top (like it always does with phenomic enabled). So, I think the phenomic behaviour and the browser behaviour seemed aligned and we can consider the issue closed :)

**Comment by davidtheclark** [comment]
Eh ... I'm not seeing it working like it's supposed to. For example:

- Go to a non-phenomic URL with a hash like https://github.com/stylelint/stylelint#need-help or https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_access_path_mode_callback and refresh. Every time I refresh, I am brought to the "Need help" section.
- Go to http://stylelint.io/#need-help and refresh. When I arrive, I'm at the "Need help" section; but when I refresh, I end up at the top of the page.

**Pull request merged**
