### PR TITLE
Demo linter

### PR DESCRIPTION
**Pull request by m-allanson**
This is not ready to merge yet.

You can test this branch by running `npm start` and browsing to `http://0.0.0.0:3000/demo/`.

## Approach

Syntax highlighting and line numbers are included thanks to [CodeMirror](https://codemirror.net/)

I've created a [standalone stylelint browser bundle](https://github.com/m-allanson/stylelint-browser-bundle.git) which is imported by the `Demo` component.

A [loader](https://github.com/stylelint/stylelint.io/blob/c4fa9b926a20bbf4e72c9aa463dacc67886ac1f6/web_modules/Demo/loader.js) is used to tell webpack to create a second js chunk which can be loaded on demand. This chunk is requested when a user hits the `/demo` route.

## Problems

This approach broadly works, but there are some areas that need improvement:

- ~~The build task now takes 10 - 15 minutes (on my machine)~~
- The demo js file is 1.7MB (after minification) 
- There are no tests
- ~~The CodeMirror CSS is being loaded with link tags pointing to `https://rawgit.com`~~
- ~~It relies on my standalone stylelint browser bundle~~

I'll be away for the next few days, so wanted to get this online for people to comment on. Feedback is very welcome, as always :)

Refs #2

### CODE REVIEW

**Comment by MoOx** [comment]
1.7MB seems big, cssnext standalone playground is 1MB (and contains caniuse database!).
10/15min, it looks like there is a problem somewhere :/

Anyway, the idea looks good :)

**Comment by m-allanson** [comment]
That's good to know, I can look at webpack's stats output and see if that size can be trimmed down.

**Comment by davidtheclark** [comment]
I'm unable to get it running in the browser ... just spins indefinitely ... maybe same problem that is causing the 15 minute build?

Whatever it is, thanks for championing this! I'm sure you'll figure out the problems.

**Comment by jeddy3** [comment]
> Whatever it is, thanks for championing this!

Agreed :)

I *was* able to run it. It took about minute using `npm start` to fire up. It's fantastic and very exciting to see stylelint in the browser!

@davidtheclark I did have to disable uBlock origin for `localhost` and refresh the browser window a couple of times. So, a few niggles to work out. But as a 1st draft it is looking great! There are two code windows (with line numbers and syntax highlighting) and the warnings update on every keystroke. It's super demo and I think it will really shows stylelint in a good light :)

**Comment by jeddy3** [comment]
I figured I'd take a quick stab at evolving the styling whilst Mike is away. There's probably a neater way of coding it...

Anyhow, looks like this now:

screen shot 2016-04-16 at 17 30 14

Changes include:

- Showing the severity.
- Linking to each rule's documentation.
- Shrinking down the line numbers column so it fits better on a smaller viewport.

I'm afraid I won't have time to look into addressing the problems listed above, and so I'm looking forward to seeing how @m-allanson gets on when he gets back :)

**Comment by m-allanson** [comment]
I've been chipping away at this and have come to wonder if integrating the demo directly into the docs site is the best approach. 

The stylelint browser bundle (used by the demo) is created by replacing certain parts of stylelint. This works but can be quite fragile - changes to stylelint occasionally require the browser bundling config to be updated.

I can foresee a situation where the docs site can't be updated until the browser bundling config has also been updated to accommodate changes in stylelint. Updating the docs site seems like a task that should always be simple and reliable.

Could this be solved by spinning the demo off into its own repo? Maybe as a React component or something that could be imported via an iframe. Or is it ok to continue with the current approach and deal with bundling issues as they arise?

--

I've pushed the latest code which fixes some of the issues mentioned at the top of this conversation. In particular, the build times should be more reasonable now.

**Comment by davidtheclark** [comment]
Can you give a little more explanation of what "dealing with bundling issues" might look like?

**Comment by jeddy3** [comment]
Oops, that was a disastrous rebase. I'm not sure what happened. Hopefully we can squash all this down on merge. Anyway, all the changes from phenomic `0.10` -> `0.12` should be in this branch now. I also updated the output to match the new string formatter colour scheme introduced in `6.3.`.

@m-allanson Thanks for chipping away at this!

**Comment by m-allanson** [comment]
@davidtheclark Yes, I encountered one problem which I'll detail here. 

While working on this PR, there were some changes to buildConfig (I think [in stylelint v6.1.0](https://github.com/stylelint/stylelint/compare/6.0.3...6.1.0#diff-7)) which resulted in a TypeError error when running the demo. The error occurred at runtime, not when webpack bundled the files.

screen shot 2016-05-10 at 14 29 08

I worked around this by writing [a shim for buildConfig](https://github.com/stylelint/stylelint.io/blob/demo-linter/scripts/bundle-stylelint/build-config-shim.js) and [updating the webpack config](https://github.com/stylelint/stylelint.io/blob/demo-linter/scripts/bundle-stylelint/webpack.config.babel.js#L39-L44) to include it in place of stylelint's own buildConfig module.

**Comment by davidtheclark** [comment]
Makes sense. I'm happy for ya'll to do whatever you think is best. For my own sanity I'm kind of staying out of this one.

**Comment by m-allanson** [comment]
I've taken some of the work here and come up with an alternate approach. Closing this PR.

**Pull request closed without merging**
