### PR TITLE
Fix strange changelog headings

### LINKED ISSUE #69: Improve changelog Table of Content
Currently all links looks like “[10.1.0][]”.

> Yes, it's strange. When I research it, I find that the behavior is due to the internal code of `docusaurus` and `markdown-toc`. See below:
> 
> - https://github.com/facebook/docusaurus/blob/v1.11.1/packages/docusaurus-1.x/lib/core/toc.js#L29
> - https://github.com/jonschlinkert/markdown-toc/blob/1.2.0/index.js#L209

_Originally posted by @ybiquitous in https://github.com/stylelint/stylelint.io/pull/67#issuecomment-509704539_

https://stylelint.io/changelog/

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #69 

> Is there anything in the PR that needs further explanation?

By adding a new custom `remark` plugin, headings in `CHANGELOG.md` are changed like this:

```diff
-## [10.1.0][]
+## 10.1.0
+
+[Full diff][10.1.0]
 
 -   Added: `selector-max-empty-lines` autofix ([#3717](https://github.com/stylelint/stylelint/pull/3717)).
```

### CODE REVIEW

**Comment by hudochenkov** [comment]
We might not need this fix. I've opened discussion to simplify changelog https://github.com/stylelint/stylelint/issues/4166

**Comment by ybiquitous** [comment]
This PR is already unneeded, thanks to @hudochenkov.

**Comment by hudochenkov** [comment]
Sorry you have to spend your time on this.

**Comment by ybiquitous** [comment]
Don't mind! 😄

**Pull request closed without merging**
