### PR TITLE
Add a 'Demo' page

### PR DESCRIPTION
**Pull request by m-allanson**
Refs #2 

The content of the demo page is just an iframe pointing to http://stylelint-demo.herokuapp.com

### CODE REVIEW

**Comment by m-allanson** [comment]
I think this build is failing due to https://github.com/stylelint/stylelint/issues/1616

**Comment by jeddy3** [comment]
Excellent work!

I've tweaked the navigation to avoid wrapping. This PR LGTM now.

**Comment by ntwb** [comment]
Awesome @m-allanson 👍

**Comment by ntwb** [comment]
@davidtheclark @jeddy3 We should compose an awesome tweet for http://stylelint.io/demo/

**Comment by ntwb** [comment]
Or include the "demo" announcement as part of the fanfare that will be the stylelint v7 tweet?

**Pull request merged**
