### PR TITLE
Add favicon and Open Graph tags

### LINKED ISSUE #12: Add favicon
Favicon is very important, because users use them to find link in bookmarks. Also you should add OpenGraph image, because it is very important for pormotion.

You can take favicons sizes from postcss.org website: https://github.com/postcss/postcss.org/tree/9fbc10c0b756e970176edbf57c6c8a3aba408a13/web_modules/LayoutContainer
* 48×48 `favicon.ico`
* 192×192 for touch devices
* 1200×630 for OpenGraph

### PR DESCRIPTION
**Pull request by m-allanson**
Closes #12 

The images are taken from [the identity section of the main stylelint repo](https://github.com/stylelint/stylelint/tree/master/identity).

### CODE REVIEW

**Comment by MoOx** [comment]
Curious to know why did you choose to have 2 favicons (and why this size? btw what size have the favicon.ico?)

**Comment by m-allanson** [comment]
@MoOx Honestly I didn't put much thought into it, the sizes are based on [the sizes used by postcss.org](https://github.com/postcss/postcss.org/tree/master/web_modules/LayoutContainer). The favicon is 48x48.

I could update this PR to support [more favicon sizes](https://github.com/audreyr/favicon-cheat-sheet). If we have visitor stats for stylelint.io, maybe I should add icon sizes for the most popular browsers?

**Comment by MoOx** [comment]
No idea what are the best practices for favicons. That's why I was curious. This days having to serve 20 favicons or more seems crazy.

**Comment by jeddy3** [comment]
Thanks!

**Comment by jeddy3** [comment]
That's weird. It worked fine on `localhost`, but on stylelint.io there's a 404 error: http://stylelint.io/_/web_modules/LayoutContainer/favicon-192x192.png

Any ideas?

@m-allanson BTW, `npm run deploy` pushes the site to stylelint.io. It's very unlikely to break anything, so feel free to push up the site whenever. For example, if you've time to look into this 404 error.

**Comment by m-allanson** [comment]
How strange.

This url returns a 404:
```
http://stylelint.io/_/web_modules/LayoutContainer/favicon-192x192.png
```

These urls return an image:
```
http://localhost:3000/_/web_modules/LayoutContainer/favicon-192x192.png
https://raw.githubusercontent.com/stylelint/stylelint.github.io/master/_/web_modules/LayoutContainer/favicon-192x192.png
```

For reference, the urls over at postcss look like this:
```

**Comment by MoOx** [comment]
_/* are generated by webpack, it's a sort of "hack" to remove the context of the source were webpack is builded. This is generated by the `[path]` part in the config https://github.com/stylelint/stylelint.io/blob/master/webpack.config.babel.js#L57.

The thing is, github pages assume by default that your project is a jekyll project, so run the engine on it everytime (yeah your read correctly). By default all _ folder are ignored by the publish step of jekyll. The workaround is to add a .nojekyll file at the root. Phenomic handles this by default since 0.7.0.
Just add `nojekyll: true,` in the `phenomic` config in your package.json and the file will be generated after the build so your deploy step will have it.

Also about sizes: https://github.com/postcss/postcss.org/pull/193#issuecomment-229636092

**Comment by jeddy3** [comment]
@MoOx Thanks! That did the trick :)

I'll keep an eye on that favicon size convo too.

**Pull request merged**
